
image: docker:latest
services:
  - docker:dind
stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  image: node:16.18.0-alpine
  script:
    - npm install
    - npm run build

test:
  stage: test
  image: node:16.18.0-alpine
  script:
    - npm install
    - npm run test

package:
  stage: package
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u reda91 -p $DOCKER_HUB_PASSWORD
  script:
    - docker build -t reda91/client .
    - docker push reda91/client:latest

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker pull reda91/client:latest
    - docker run -d --name client_container -p 8080:80 reda91/client:latest


