# Use the official Node.js image as the base image
FROM node:16

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

COPY . .

EXPOSE 8000

# Start the application
CMD ["npm", "run", "start"]
