include:
  - project: 'DiagAI/client'
    file: 'DiagAI/client/.gitlab-ci.yml'
  - project: 'DiagAI/flask-server'
    file: 'DiagAI/flask-server/.gitlab-ci.yml'
  - project: 'DiagAI/server'
    file: 'DiagAI/server/.gitlab-ci.yml'
  
