include:
  - project: https://gitlab.com/Reedaa/diagai
    file: /client/.gitlab-ci.yml
  - project: https://gitlab.com/Reedaa/diagai
    file: /flask-server/.gitlab-ci.yml
  - project: https://gitlab.com/Reedaa/diagai
    file: /server/.gitlab-ci.yml
  
