stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: python:3.8-alpine
  script:
    - pip install -r requirements.txt
    # Add any additional build steps here

test:
  stage: test
  image: python:3.8-alpine
  script:
    - pip install -r requirements.txt
    - python -m unittest discover tests/

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u reda91 -p $DOCKER_HUB_PASSWORD
  script:
    - docker build -t reda91/pyhton .
    - docker push reda91/python:latest
    - docker pull reda91/python:latest
    - docker run -d --name python_container -p 8080:80 reda91/python:latest
