apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: server
          image: reda91/client
          ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: client-deployment
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: reda91/python
          ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: python-deployment
spec:
  type: ClusterIP
  selector:
    app: pyhton
  ports:
  - name: http
    port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: reda91/server
          ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: server-deployment
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
  - name: http
    port: 80
    targetPort: 8080

